-- ============================================================
--  LOGIX FOR STA SEYCHELLES — ON-SITE CLOCK-IN ENFORCEMENT
-- ============================================================
--  Run AFTER harden_auth_and_rls.sql
--
--  GOAL: stop staff clocking in from home.
--
--  WHY NOT "CHECK THE WIFI NAME": browsers cannot read the SSID of
--  the network the device is on. There is no web API for it, on any
--  browser, by design (privacy). Only a native iOS/Android app can.
--  So we verify the two things a browser CAN prove, server-side:
--
--    1. NETWORK  — the device's public IP must fall inside a CIDR
--                  range registered for the campus. Someone on the
--                  STA WiFi shares the academy's public IP; someone
--                  at home does not. This is the practical
--                  equivalent of "must be on the office WiFi".
--    2. LOCATION — GPS coordinates must be inside a geofence.
--
--  Both are checked in the database, not the browser, so editing the
--  page in devtools cannot bypass them.
--
--  IMPORTANT ON IP SPOOFING: a client CAN send its own
--  X-Forwarded-For header. Supabase does not overwrite it — it
--  APPENDS the true client IP. So the spoofed value lands on the
--  LEFT and the trustworthy one is the RIGHTMOST entry. Most code
--  samples online read the leftmost entry, which is exactly the
--  spoofable one. We read the rightmost, and prefer Cloudflare's
--  cf-connecting-ip when present (the edge sets it; clients cannot).
-- ============================================================

-- ------------------------------------------------------------
-- 1. Worksites + their registered networks
-- ------------------------------------------------------------
create table if not exists public.worksites (
  id bigint generated by default as identity primary key,
  name text not null,
  latitude double precision,
  longitude double precision,
  radius_meters integer not null default 200,
  require_network boolean not null default true,
  require_location boolean not null default true,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default now()
);

create table if not exists public.worksite_networks (
  id bigint generated by default as identity primary key,
  worksite_id bigint not null references public.worksites(id) on delete cascade,
  cidr cidr not null,
  label text,
  created_at timestamp with time zone not null default now()
);

-- Every clock attempt, allowed or denied. This is the fraud record.
create table if not exists public.clock_events (
  id bigint generated by default as identity primary key,
  employee_id bigint references public.employees(id) on delete set null,
  action text not null,
  allowed boolean not null,
  denial_reason text,
  ip inet,
  latitude double precision,
  longitude double precision,
  accuracy_meters double precision,
  distance_meters double precision,
  user_agent text,
  created_at timestamp with time zone not null default now()
);
create index if not exists idx_clock_events_created on public.clock_events (created_at desc);
create index if not exists idx_clock_events_allowed on public.clock_events (allowed, created_at desc);

-- Record where each clock punch actually happened
alter table public.attendance
  add column if not exists clock_in_ip inet,
  add column if not exists clock_out_ip inet,
  add column if not exists clock_in_lat double precision,
  add column if not exists clock_in_lng double precision,
  add column if not exists clock_out_lat double precision,
  add column if not exists clock_out_lng double precision;

alter table public.worksites enable row level security;
alter table public.worksite_networks enable row level security;
alter table public.clock_events enable row level security;

revoke all on public.worksites from anon, authenticated;
revoke all on public.worksite_networks from anon, authenticated;
revoke all on public.clock_events from anon, authenticated;
-- Read access only, and only through explicit grants; all writes go
-- through the SECURITY DEFINER functions below.
grant select on public.worksites to anon, authenticated;
grant select on public.worksite_networks to anon, authenticated;
grant select on public.clock_events to anon, authenticated;

create policy "read_worksites" on public.worksites for select using (true);
create policy "read_worksite_networks" on public.worksite_networks for select using (true);
create policy "read_clock_events" on public.clock_events for select using (true);

-- ------------------------------------------------------------
-- 2. Trustworthy client IP
-- ------------------------------------------------------------
create or replace function public.request_client_ip() returns inet
language plpgsql stable security definer set search_path = public, extensions as $$
declare
  v_headers json;
  v_raw text;
  v_parts text[];
  v_candidate text;
begin
  begin
    v_headers := current_setting('request.headers', true)::json;
  exception when others then
    return null;
  end;
  if v_headers is null then
    return null;
  end if;

  -- Cloudflare sets this at the edge; a client cannot forge it.
  v_raw := v_headers->>'cf-connecting-ip';
  if v_raw is not null and length(trim(v_raw)) > 0 then
    begin
      return trim(v_raw)::inet;
    exception when others then
      null; -- fall through
    end;
  end if;

  -- Rightmost X-Forwarded-For entry = appended by the platform = real.
  v_raw := v_headers->>'x-forwarded-for';
  if v_raw is null or length(trim(v_raw)) = 0 then
    return null;
  end if;

  v_parts := string_to_array(v_raw, ',');
  v_candidate := trim(v_parts[array_length(v_parts, 1)]);

  begin
    return v_candidate::inet;
  exception when others then
    return null;
  end;
end;
$$;
revoke all on function public.request_client_ip() from public;

-- ------------------------------------------------------------
-- 3. Great-circle distance in metres
-- ------------------------------------------------------------
create or replace function public.haversine_meters(
  lat1 double precision, lon1 double precision,
  lat2 double precision, lon2 double precision
) returns double precision
language plpgsql immutable as $$
declare
  r constant double precision := 6371000; -- earth radius, metres
  dlat double precision;
  dlon double precision;
  a double precision;
begin
  if lat1 is null or lon1 is null or lat2 is null or lon2 is null then
    return null;
  end if;
  dlat := radians(lat2 - lat1);
  dlon := radians(lon2 - lon1);
  a := sin(dlat / 2) ^ 2
     + cos(radians(lat1)) * cos(radians(lat2)) * sin(dlon / 2) ^ 2;
  return r * 2 * asin(least(1, sqrt(a)));
end;
$$;

-- ------------------------------------------------------------
-- 4. Evaluate whether a clock attempt is on-site
-- ------------------------------------------------------------
--  Returns (allowed, reason, distance). If no active worksite is
--  configured yet, enforcement is OFF so the migration cannot lock
--  the whole academy out on day one. The admin UI flags this loudly.
create or replace function public.evaluate_onsite(
  p_ip inet, p_lat double precision, p_lng double precision
) returns table(allowed boolean, reason text, distance_meters double precision)
language plpgsql stable security definer set search_path = public, extensions as $$
declare
  v_site record;
  v_dist double precision;
  v_net_ok boolean;
  v_any_site boolean := false;
begin
  for v_site in select * from public.worksites where is_active order by id loop
    v_any_site := true;

    -- Network check
    v_net_ok := true;
    if v_site.require_network then
      if p_ip is null then
        v_net_ok := false;
      else
        select exists (
          select 1 from public.worksite_networks wn
          where wn.worksite_id = v_site.id and p_ip <<= wn.cidr
        ) into v_net_ok;
      end if;
    end if;

    -- Location check
    v_dist := null;
    if v_site.require_location and v_site.latitude is not null then
      if p_lat is null or p_lng is null then
        if v_net_ok then
          continue; -- network matched but no GPS: try other sites, else deny below
        end if;
        continue;
      end if;
      v_dist := public.haversine_meters(p_lat, p_lng, v_site.latitude, v_site.longitude);
      if v_dist > v_site.radius_meters then
        continue;
      end if;
    end if;

    if v_net_ok then
      return query select true, null::text, v_dist;
      return;
    end if;
  end loop;

  if not v_any_site then
    -- Nothing configured yet — allow, but say so.
    return query select true, 'unconfigured'::text, null::double precision;
    return;
  end if;

  return query select false,
    'You must be on the academy network and on site to clock in.'::text,
    null::double precision;
end;
$$;
revoke all on function public.evaluate_onsite(inet, double precision, double precision) from public;

-- ------------------------------------------------------------
-- 5. Clock in/out with enforcement
-- ------------------------------------------------------------
drop function if exists public.clock_action(uuid, text);

create or replace function public.clock_action(
  p_token uuid,
  p_action text,
  p_lat double precision default null,
  p_lng double precision default null,
  p_accuracy double precision default null
) returns public.attendance
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_session record;
  v_ip inet;
  v_check record;
  v_row public.attendance;
  v_now timestamptz := now();
  v_ua text;
begin
  select * into v_session from public._require_session(p_token, false);

  if p_action not in ('in', 'out') then
    raise exception 'Invalid clock action';
  end if;

  v_ip := public.request_client_ip();
  begin
    v_ua := (current_setting('request.headers', true)::json)->>'user-agent';
  exception when others then
    v_ua := null;
  end;

  select * into v_check from public.evaluate_onsite(v_ip, p_lat, p_lng);

  if not v_check.allowed then
    insert into public.clock_events (
      employee_id, action, allowed, denial_reason, ip,
      latitude, longitude, accuracy_meters, distance_meters, user_agent
    ) values (
      v_session.employee_id, p_action, false, v_check.reason, v_ip,
      p_lat, p_lng, p_accuracy, v_check.distance_meters, v_ua
    );
    raise exception '%', v_check.reason;
  end if;

  insert into public.clock_events (
    employee_id, action, allowed, denial_reason, ip,
    latitude, longitude, accuracy_meters, distance_meters, user_agent
  ) values (
    v_session.employee_id, p_action, true, v_check.reason, v_ip,
    p_lat, p_lng, p_accuracy, v_check.distance_meters, v_ua
  );

  insert into public.attendance (
    employee_id, date, clock_in, clock_out, updated_at,
    clock_in_ip, clock_out_ip, clock_in_lat, clock_in_lng, clock_out_lat, clock_out_lng
  ) values (
    v_session.employee_id, current_date,
    case when p_action = 'in' then v_now end,
    case when p_action = 'out' then v_now end,
    v_now,
    case when p_action = 'in' then v_ip end,
    case when p_action = 'out' then v_ip end,
    case when p_action = 'in' then p_lat end,
    case when p_action = 'in' then p_lng end,
    case when p_action = 'out' then p_lat end,
    case when p_action = 'out' then p_lng end
  )
  on conflict (employee_id, date) do update set
    clock_in     = case when p_action = 'in'  then v_now else public.attendance.clock_in end,
    clock_out    = case when p_action = 'out' then v_now else public.attendance.clock_out end,
    clock_in_ip  = case when p_action = 'in'  then v_ip  else public.attendance.clock_in_ip end,
    clock_out_ip = case when p_action = 'out' then v_ip  else public.attendance.clock_out_ip end,
    clock_in_lat = case when p_action = 'in'  then p_lat else public.attendance.clock_in_lat end,
    clock_in_lng = case when p_action = 'in'  then p_lng else public.attendance.clock_in_lng end,
    clock_out_lat= case when p_action = 'out' then p_lat else public.attendance.clock_out_lat end,
    clock_out_lng= case when p_action = 'out' then p_lng else public.attendance.clock_out_lng end,
    updated_at   = v_now
  returning * into v_row;

  return v_row;
end;
$$;
revoke all on function public.clock_action(uuid, text, double precision, double precision, double precision) from public;
grant execute on function public.clock_action(uuid, text, double precision, double precision, double precision) to anon, authenticated;

-- ------------------------------------------------------------
-- 6. Let the app tell the user WHY before they tap the button
-- ------------------------------------------------------------
create or replace function public.check_clock_eligibility(
  p_token uuid, p_lat double precision default null, p_lng double precision default null
) returns json
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_ip inet;
  v_check record;
begin
  perform public._require_session(p_token, false);
  v_ip := public.request_client_ip();
  select * into v_check from public.evaluate_onsite(v_ip, p_lat, p_lng);
  return json_build_object(
    'allowed', v_check.allowed,
    'reason', v_check.reason,
    'distance_meters', v_check.distance_meters,
    'enforced', exists(select 1 from public.worksites where is_active)
  );
end;
$$;
revoke all on function public.check_clock_eligibility(uuid, double precision, double precision) from public;
grant execute on function public.check_clock_eligibility(uuid, double precision, double precision) to anon, authenticated;

-- Admin setup helper: "what IP am I on right now?"
create or replace function public.my_network_info(p_token uuid) returns json
language plpgsql security definer set search_path = public, extensions as $$
begin
  perform public._require_session(p_token, true);
  return json_build_object('ip', host(public.request_client_ip()));
end;
$$;
revoke all on function public.my_network_info(uuid) from public;
grant execute on function public.my_network_info(uuid) to anon, authenticated;

-- ------------------------------------------------------------
-- 7. Admin management of worksites & networks
-- ------------------------------------------------------------
create or replace function public.admin_save_worksite(
  p_token uuid, p_id bigint, p_name text,
  p_lat double precision, p_lng double precision, p_radius integer,
  p_require_network boolean, p_require_location boolean, p_is_active boolean
) returns public.worksites
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_row public.worksites;
begin
  perform public._require_session(p_token, true);

  if p_id is null then
    insert into public.worksites (name, latitude, longitude, radius_meters, require_network, require_location, is_active)
    values (p_name, p_lat, p_lng, coalesce(p_radius, 200), coalesce(p_require_network, true), coalesce(p_require_location, true), coalesce(p_is_active, true))
    returning * into v_row;
  else
    update public.worksites set
      name = p_name, latitude = p_lat, longitude = p_lng,
      radius_meters = coalesce(p_radius, 200),
      require_network = coalesce(p_require_network, true),
      require_location = coalesce(p_require_location, true),
      is_active = coalesce(p_is_active, true)
    where id = p_id
    returning * into v_row;
  end if;

  return v_row;
end;
$$;
revoke all on function public.admin_save_worksite(uuid, bigint, text, double precision, double precision, integer, boolean, boolean, boolean) from public;
grant execute on function public.admin_save_worksite(uuid, bigint, text, double precision, double precision, integer, boolean, boolean, boolean) to anon, authenticated;

create or replace function public.admin_add_network(p_token uuid, p_worksite_id bigint, p_cidr text, p_label text)
returns public.worksite_networks
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_row public.worksite_networks;
  v_cidr cidr;
begin
  perform public._require_session(p_token, true);
  begin
    -- A bare address like 41.20.30.40 becomes a /32 host route.
    v_cidr := p_cidr::cidr;
  exception when others then
    raise exception 'Not a valid IP address or CIDR range: %', p_cidr;
  end;

  insert into public.worksite_networks (worksite_id, cidr, label)
  values (p_worksite_id, v_cidr, p_label)
  returning * into v_row;
  return v_row;
end;
$$;
revoke all on function public.admin_add_network(uuid, bigint, text, text) from public;
grant execute on function public.admin_add_network(uuid, bigint, text, text) to anon, authenticated;

create or replace function public.admin_delete_network(p_token uuid, p_id bigint) returns void
language plpgsql security definer set search_path = public, extensions as $$
begin
  perform public._require_session(p_token, true);
  delete from public.worksite_networks where id = p_id;
end;
$$;
revoke all on function public.admin_delete_network(uuid, bigint) from public;
grant execute on function public.admin_delete_network(uuid, bigint) to anon, authenticated;

-- ============================================================
-- DONE.
--
-- SETUP, ONCE, FROM THE ADMIN DASHBOARD → "Site security" tab:
--   1. While physically on the STA WiFi, click "Use my current IP".
--      That registers the academy's public address.
--   2. Click "Use my current location" to drop the geofence centre,
--      set a radius (200 m is a sensible campus default).
--   3. Save. Enforcement is live from that moment.
--
-- CAVEATS, STATED PLAINLY:
--   * If the academy's ISP hands out a DYNAMIC public IP, it will
--     change eventually and staff will be blocked until you re-add
--     it. Ask the ISP for a static IP, or rely on the geofence.
--   * Staff on mobile data standing in the car park will fail the
--     network check but pass the geofence. Decide which you want:
--     require_network + require_location are independent toggles.
--   * A determined user can fake GPS on a rooted/developer device.
--     The IP check is the harder one to defeat; together they are
--     a strong deterrent, not an unbreakable lock. Every denied
--     attempt is recorded in clock_events for review.
-- ============================================================
