-- ============================================================
--  LOGIX — LEAVE BALANCES & PUBLIC HOLIDAYS
--  Run this AFTER password_security.sql (migration 7 of 7).
--
--  Before this file, approving leave was blind: there was no record
--  of how many days anyone was entitled to or had already used.
--  This adds entitlements, a working-day counter that skips weekends
--  and public holidays, and a balance check inside the submit path so
--  the database refuses an over-drawn request rather than trusting
--  the browser to hide the button.
-- ============================================================

-- ------------------------------------------------------------
-- 1. Public holidays
-- ------------------------------------------------------------
create table if not exists public.public_holidays (
  id          bigint generated by default as identity primary key,
  holiday_date date not null unique,
  name        text not null,
  created_at  timestamp with time zone default timezone('utc'::text, now()) not null
);

comment on table public.public_holidays is
  'Days that do not consume leave. Movable feasts (Good Friday, Easter Saturday, Corpus Christi) shift each year and must be added by an administrator.';

-- Fixed-date Seychelles public holidays for 2026 and 2027.
-- VERIFY THESE against the official Government of Seychelles gazette before
-- relying on them for payroll, and add the movable feasts for each year.
insert into public.public_holidays (holiday_date, name) values
  ('2026-01-01', 'New Year''s Day'),
  ('2026-01-02', 'New Year Holiday'),
  ('2026-05-01', 'Labour Day'),
  ('2026-06-18', 'Constitution Day'),
  ('2026-06-29', 'Independence (National) Day'),
  ('2026-08-15', 'Assumption Day'),
  ('2026-11-01', 'All Saints'' Day'),
  ('2026-12-08', 'Feast of the Immaculate Conception'),
  ('2026-12-25', 'Christmas Day'),
  ('2027-01-01', 'New Year''s Day'),
  ('2027-01-02', 'New Year Holiday'),
  ('2027-05-01', 'Labour Day'),
  ('2027-06-18', 'Constitution Day'),
  ('2027-06-29', 'Independence (National) Day'),
  ('2027-08-15', 'Assumption Day'),
  ('2027-11-01', 'All Saints'' Day'),
  ('2027-12-08', 'Feast of the Immaculate Conception'),
  ('2027-12-25', 'Christmas Day')
on conflict (holiday_date) do nothing;


-- ------------------------------------------------------------
-- 2. Default entitlement per leave type
-- ------------------------------------------------------------
-- leave_types.max_days_per_year already exists but was never populated.
-- A null means "not capped" - the type is available without a balance.
update public.leave_types set max_days_per_year = 21 where code = 'AL' and max_days_per_year is null;
update public.leave_types set max_days_per_year = 21 where code = 'SL' and max_days_per_year is null;
update public.leave_types set max_days_per_year =  5 where code = 'CL' and max_days_per_year is null;
update public.leave_types set max_days_per_year =  5 where code = 'EL' and max_days_per_year is null;
update public.leave_types set max_days_per_year = 10 where code = 'STL' and max_days_per_year is null;
-- Maternity and paternity are left uncapped deliberately; they are governed
-- by statute rather than an annual allowance.


-- ------------------------------------------------------------
-- 3. Per-employee overrides
-- ------------------------------------------------------------
create table if not exists public.leave_entitlements (
  id            bigint generated by default as identity primary key,
  employee_id   bigint not null references public.employees(id) on delete cascade,
  leave_type_id bigint not null references public.leave_types(id) on delete cascade,
  year          int not null,
  days_entitled numeric(5,1) not null check (days_entitled >= 0),
  note          text,
  created_at    timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (employee_id, leave_type_id, year)
);

comment on table public.leave_entitlements is
  'Overrides leave_types.max_days_per_year for one person in one year. Absent row means the type default applies.';

create index if not exists leave_entitlements_lookup
  on public.leave_entitlements (employee_id, year);


-- ------------------------------------------------------------
-- 4. Working-day counter
-- ------------------------------------------------------------
-- Counts Mon-Fri days between two dates inclusive, skipping public holidays.
-- A half day counts as 0.5 and is only meaningful on a single-day request.
create or replace function public.count_leave_days(
  p_start date, p_end date, p_half_day boolean default false
) returns numeric
language sql stable security definer set search_path = public, extensions as $$
  select case
    when p_start is null or p_end is null or p_end < p_start then 0
    when coalesce(p_half_day, false) and p_start = p_end then 0.5
    else (
      select count(*)::numeric
      from generate_series(p_start, p_end, interval '1 day') as d(day)
      where extract(isodow from d.day) < 6
        and not exists (
          select 1 from public.public_holidays h
          where h.holiday_date = d.day::date
        )
    )
  end;
$$;


-- ------------------------------------------------------------
-- 5. Balance calculation
-- ------------------------------------------------------------
-- Returns one row per capped leave type: entitled, used, remaining.
-- "Used" counts approved requests only; pending is reported separately so
-- staff can see what is still awaiting a decision.
create or replace function public._leave_balances(p_employee_id bigint, p_year int)
returns table (
  leave_code   text,
  leave_name   text,
  color        text,
  entitled     numeric,
  used         numeric,
  pending      numeric,
  remaining    numeric
)
language sql stable security definer set search_path = public, extensions as $$
  select
    lt.code,
    lt.name,
    lt.color,
    ent.days                                        as entitled,
    coalesce(tally.approved, 0)                     as used,
    coalesce(tally.pending, 0)                      as pending,
    greatest(ent.days - coalesce(tally.approved, 0), 0) as remaining
  from public.leave_types lt
  cross join lateral (
    select coalesce(
      (select le.days_entitled
         from public.leave_entitlements le
        where le.employee_id = p_employee_id
          and le.leave_type_id = lt.id
          and le.year = p_year),
      lt.max_days_per_year
    )::numeric as days
  ) ent
  left join lateral (
    select
      sum(public.count_leave_days(lr.start_date, lr.end_date, lr.is_half_day))
        filter (where lr.status = 'approved') as approved,
      sum(public.count_leave_days(lr.start_date, lr.end_date, lr.is_half_day))
        filter (where lr.status = 'pending')  as pending
    from public.leave_requests lr
    where lr.employee_id = p_employee_id
      and lr.leave_type_id = lt.id
      and extract(year from lr.start_date) = p_year
  ) tally on true
  where lt.is_active
    and ent.days is not null      -- uncapped types carry no balance
  order by lt.name;
$$;


-- Employee-facing: my own balances for a given year (defaults to this year).
create or replace function public.my_leave_balances(p_token uuid, p_year int default null)
returns table (
  leave_code text, leave_name text, color text,
  entitled numeric, used numeric, pending numeric, remaining numeric
)
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_session record;
  v_year int := coalesce(p_year, extract(year from current_date)::int);
begin
  select * into v_session from public._require_session(p_token, false);
  return query select * from public._leave_balances(v_session.employee_id, v_year);
end;
$$;


-- Admin-facing: anyone's balances.
create or replace function public.admin_leave_balances(
  p_token uuid, p_employee_id bigint, p_year int default null
)
returns table (
  leave_code text, leave_name text, color text,
  entitled numeric, used numeric, pending numeric, remaining numeric
)
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_session record;
  v_year int := coalesce(p_year, extract(year from current_date)::int);
begin
  select * into v_session from public._require_session(p_token, true);
  return query select * from public._leave_balances(p_employee_id, v_year);
end;
$$;


-- ------------------------------------------------------------
-- 6. Enforce the balance when a request is submitted
-- ------------------------------------------------------------
-- Replaces the version in harden_auth_and_rls.sql. Same signature, so the
-- front end needs no change to keep working - it just gets a clear error
-- instead of silently over-drawing.
create or replace function public.submit_leave_request(
  p_token uuid, p_leave_code text, p_start date, p_end date,
  p_reason text, p_half_day boolean
) returns public.leave_requests
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_session       record;
  v_type          record;
  v_row           public.leave_requests;
  v_days          numeric;
  v_remaining     numeric;
  v_pending       numeric;
  v_year          int;
begin
  select * into v_session from public._require_session(p_token, false);

  select id, name, max_days_per_year into v_type
    from public.leave_types where code = p_leave_code and is_active;
  if v_type.id is null then
    raise exception 'Unknown leave type';
  end if;

  if p_start is null or p_end is null then
    raise exception 'A start and end date are both required';
  end if;
  if p_end < p_start then
    raise exception 'The end date cannot be before the start date';
  end if;
  if coalesce(p_half_day, false) and p_start <> p_end then
    raise exception 'A half day must start and end on the same date';
  end if;

  v_days := public.count_leave_days(p_start, p_end, p_half_day);
  if v_days = 0 then
    raise exception 'That range contains no working days - it is all weekend or public holiday';
  end if;

  -- Overlap guard: two approved or pending requests on the same days is
  -- almost always a double submission rather than an intention.
  if exists (
    select 1 from public.leave_requests lr
    where lr.employee_id = v_session.employee_id
      and lr.status in ('pending', 'approved')
      and lr.start_date <= p_end
      and lr.end_date   >= p_start
  ) then
    raise exception 'You already have a leave request covering some of those dates';
  end if;

  -- Balance check, for capped types only.
  if v_type.max_days_per_year is not null then
    v_year := extract(year from p_start)::int;

    select b.remaining, b.pending into v_remaining, v_pending
      from public._leave_balances(v_session.employee_id, v_year) b
     where b.leave_code = p_leave_code;

    if coalesce(v_remaining, 0) - coalesce(v_pending, 0) < v_days then
      raise exception
        '% days requested but only % left for % in % (% already awaiting approval)',
        v_days,
        greatest(coalesce(v_remaining, 0) - coalesce(v_pending, 0), 0),
        v_type.name, v_year, coalesce(v_pending, 0);
    end if;
  end if;

  insert into public.leave_requests
    (employee_id, leave_type_id, start_date, end_date, reason, is_half_day)
  values
    (v_session.employee_id, v_type.id, p_start, p_end, p_reason, coalesce(p_half_day, false))
  returning * into v_row;

  return v_row;
end;
$$;


-- ------------------------------------------------------------
-- 7. Let an administrator set an entitlement
-- ------------------------------------------------------------
create or replace function public.admin_set_entitlement(
  p_token uuid, p_employee_id bigint, p_leave_code text,
  p_year int, p_days numeric, p_note text default null
) returns void
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_session   record;
  v_type_id   bigint;
  v_actor     text;
  v_target    text;
begin
  select * into v_session from public._require_session(p_token, true);

  select id into v_type_id from public.leave_types where code = p_leave_code;
  if v_type_id is null then
    raise exception 'Unknown leave type';
  end if;
  if p_days < 0 then
    raise exception 'Entitlement cannot be negative';
  end if;

  insert into public.leave_entitlements (employee_id, leave_type_id, year, days_entitled, note)
  values (p_employee_id, v_type_id, p_year, p_days, p_note)
  on conflict (employee_id, leave_type_id, year)
  do update set days_entitled = excluded.days_entitled, note = excluded.note;

  select full_name into v_actor  from public.employees where id = v_session.employee_id;
  select full_name into v_target from public.employees where id = p_employee_id;

  insert into public.audit_log (actor_id, actor_name, action_type, target_employee, details)
  values (v_session.employee_id, coalesce(v_actor, 'Admin'), 'SET_ENTITLEMENT',
          coalesce(v_target, ''),
          format('%s set to %s days for %s', p_leave_code, p_days, p_year));
end;
$$;


-- ------------------------------------------------------------
-- 8. Holiday management
-- ------------------------------------------------------------
create or replace function public.list_public_holidays(p_token uuid, p_year int default null)
returns table (id bigint, holiday_date date, name text)
language plpgsql security definer set search_path = public, extensions as $$
declare
  v_session record;
  v_year int := coalesce(p_year, extract(year from current_date)::int);
begin
  select * into v_session from public._require_session(p_token, false);
  return query
    select h.id, h.holiday_date, h.name
      from public.public_holidays h
     where extract(year from h.holiday_date) = v_year
     order by h.holiday_date;
end;
$$;

create or replace function public.admin_add_holiday(p_token uuid, p_date date, p_name text)
returns void
language plpgsql security definer set search_path = public, extensions as $$
declare v_session record;
begin
  select * into v_session from public._require_session(p_token, true);
  insert into public.public_holidays (holiday_date, name)
  values (p_date, p_name)
  on conflict (holiday_date) do update set name = excluded.name;
end;
$$;

create or replace function public.admin_delete_holiday(p_token uuid, p_id bigint)
returns void
language plpgsql security definer set search_path = public, extensions as $$
declare v_session record;
begin
  select * into v_session from public._require_session(p_token, true);
  delete from public.public_holidays where id = p_id;
end;
$$;


-- ------------------------------------------------------------
-- 9. Lock the new tables down, same posture as the rest
-- ------------------------------------------------------------
alter table public.public_holidays    enable row level security;
alter table public.leave_entitlements enable row level security;

-- No policies: the anon role reaches this data only through the
-- security-definer functions above, which check the session first.
revoke all on public.public_holidays    from anon, authenticated;
revoke all on public.leave_entitlements from anon, authenticated;

grant execute on function public.count_leave_days(date, date, boolean) to anon, authenticated;
grant execute on function public.my_leave_balances(uuid, int)          to anon, authenticated;
grant execute on function public.admin_leave_balances(uuid, bigint, int) to anon, authenticated;
grant execute on function public.admin_set_entitlement(uuid, bigint, text, int, numeric, text) to anon, authenticated;
grant execute on function public.list_public_holidays(uuid, int)       to anon, authenticated;
grant execute on function public.admin_add_holiday(uuid, date, text)   to anon, authenticated;
grant execute on function public.admin_delete_holiday(uuid, bigint)    to anon, authenticated;

-- _leave_balances is an internal helper; it takes no token, so it must not
-- be reachable from the browser.
revoke all on function public._leave_balances(bigint, int) from anon, authenticated;
