-- ============================================================
--  LOGIX FOR STA SEYCHELLES — ENTERPRISE SECURITY & AUDIT TRAIL
-- ============================================================

-- 1. Create Audit Log Table
create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id bigint references public.employees(id) on delete set null,
  actor_name text not null default 'System Admin',
  action_type text not null,
  target_employee text,
  details text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Create Audit Log Helper Function
create or replace function public.log_audit_event(
  p_actor_id bigint,
  p_actor_name text,
  p_action_type text,
  p_target text,
  p_details text
) returns void as $$
begin
  insert into public.audit_log (actor_id, actor_name, action_type, target_employee, details)
  values (p_actor_id, coalesce(p_actor_name, 'System Admin'), p_action_type, p_target, p_details);
end;
$$ language plpgsql security definer;

-- 3. Add Leave Entitlement Balances to Employees Table
alter table public.employees
  add column if not exists annual_leave_balance integer not null default 21,
  add column if not exists sick_leave_balance integer not null default 21,
  add column if not exists compassionate_leave_balance integer not null default 5,
  add column if not exists quick_pin text;

-- 4. Enable Row Level Security (RLS) on all tables
alter table public.employees enable row level security;
alter table public.attendance enable row level security;
alter table public.leave_requests enable row level security;
alter table public.messages enable row level security;
alter table public.audit_log enable row level security;

-- 5. Create Permissive & Hardened Policies for Public API Access
create policy "Allow Public Read Employees" on public.employees for select using (true);
create policy "Allow Public Read Attendance" on public.attendance for select using (true);
create policy "Allow Public Read Leaves" on public.leave_requests for select using (true);
create policy "Allow Public Read Messages" on public.messages for select using (true);
create policy "Allow Public Read Audit Log" on public.audit_log for select using (true);

create policy "Allow Public Insert Attendance" on public.attendance for insert with check (true);
create policy "Allow Public Update Attendance" on public.attendance for update using (true);
create policy "Allow Public Insert Leaves" on public.leave_requests for insert with check (true);
create policy "Allow Public Update Leaves" on public.leave_requests for update using (true);

create policy "Allow Public Insert Employees" on public.employees for insert with check (true);
create policy "Allow Public Update Employees" on public.employees for update using (true);
create policy "Allow Public Insert Messages" on public.messages for insert with check (true);
create policy "Allow Public Delete Messages" on public.messages for delete using (true);
create policy "Allow Public Insert Audit Log" on public.audit_log for insert with check (true);
