-- ============================================================
--  LOGIX FOR STA SEYCHELLES — SUPABASE SCHEMA
-- ============================================================

-- 1. Departments table (created first)
create table if not exists public.departments (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  description text,
  is_active boolean not null default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Employees (users) table
create table if not exists public.employees (
  id bigint generated by default as identity primary key,
  worker_id text not null unique,
  full_name text not null,
  position text not null,
  role text not null default 'worker' check (role in ('super_admin','principal','hod','teacher','worker')),
  email text unique,
  phone text,
  emergency_contact text,
  emergency_phone text,
  employment_type text not null default 'full_time',
  date_joined date,
  address text,
  department_id bigint references public.departments(id) on delete set null,
  date_of_birth date,
  photo_url text,
  password_hash text,
  must_change_password boolean not null default true,
  temp_otp text,
  otp_expires_at timestamp with time zone,
  status text not null default 'active',
  date_left date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add head_of_department reference after employees table exists
alter table public.departments 
  add column if not exists head_of_department bigint references public.employees(id) on delete set null;

-- 3. Attendance records
create table if not exists public.attendance (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  clock_in timestamp with time zone,
  clock_out timestamp with time zone,
  is_on_lunch boolean not null default false,
  lunch_started_at timestamp with time zone,
  date date not null default current_date,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique (employee_id, date)
);

-- 4. Leave types
create table if not exists public.leave_types (
  id bigint generated by default as identity primary key,
  name text not null,
  code text not null unique,
  description text,
  paid boolean not null default true,
  max_days_per_year int,
  requires_approval boolean not null default true,
  color text not null default '#3b82f6',
  is_active boolean not null default true,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Leave requests
create table if not exists public.leave_requests (
  id bigint generated by default as identity primary key,
  employee_id bigint not null references public.employees(id) on delete cascade,
  leave_type_id bigint references public.leave_types(id),
  start_date date not null,
  end_date date not null,
  reason text,
  status text not null default 'pending' check (status in ('pending','approved','denied')),
  requested_at timestamp with time zone default timezone('utc'::text, now()) not null,
  reviewed_at timestamp with time zone,
  is_half_day boolean not null default false,
  review_comment text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 6. Messages / announcements
create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  author_id bigint references public.employees(id),
  title text not null,
  body text not null,
  priority text not null default 'normal' check (priority in ('normal','important','urgent')),
  published boolean not null default true,
  published_at timestamp with time zone default timezone('utc'::text, now()),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 7. Audit log
create table if not exists public.audit_log (
  id bigint generated by default as identity primary key,
  actor_id bigint references public.employees(id),
  action text not null,
  entity text,
  entity_id bigint,
  context jsonb,
  ip text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Seed initial departments
insert into public.departments (name, code, description)
values
  ('Administration', 'ADM', 'School administration and management'),
  ('Teaching Staff', 'TCH', 'Academic teaching staff'),
  ('Support Staff', 'SUP', 'Operational support staff')
on conflict (code) do nothing;

-- Seed leave types
insert into public.leave_types (name, code, color, paid)
values
  ('Sick Leave', 'SL', '#ef4444', true),
  ('Casual Leave', 'CL', '#3b82f6', true),
  ('Maternity Leave', 'ML', '#8b5cf6', true),
  ('Paternity Leave', 'PL', '#06b6d4', true),
  ('Annual Leave', 'AL', '#10b981', true),
  ('Study Leave', 'STL', '#f59e0b', true),
  ('Emergency Leave', 'EL', '#f97316', true)
on conflict (code) do nothing;

-- Enable Row Level Security (RLS)
alter table public.departments enable row level security;
alter table public.employees enable row level security;
alter table public.attendance enable row level security;
alter table public.leave_types enable row level security;
alter table public.leave_requests enable row level security;
alter table public.messages enable row level security;
alter table public.audit_log enable row level security;

-- Open policies for client-side API access
create policy "allow_all_departments" on public.departments for all using (true) with check (true);
create policy "allow_all_employees" on public.employees for all using (true) with check (true);
create policy "allow_all_attendance" on public.attendance for all using (true) with check (true);
create policy "allow_all_leave_types" on public.leave_types for all using (true) with check (true);
create policy "allow_all_leave_requests" on public.leave_requests for all using (true) with check (true);
create policy "allow_all_messages" on public.messages for all using (true) with check (true);
create policy "allow_all_audit_log" on public.audit_log for all using (true) with check (true);
